#include <iostream>
using namespace std;
int main()
{
	int i,j,n,pt,l,temp;
	char matrix[20][20];
	while((cin>>n,n!=-1))
	{
		temp=0;
		pt=0;
		for(i=1;i<=n;i++)
			for(j=1;j<=n;j++)
				cin>>matrix[i][j];
		for(j=1;j<=n;j++)
		{
			for(l=1;l<=n;l++)
			{
				if(matrix[l][j]=='x')
					temp++;
				else
				{
					if(temp>3)
						pt+=temp-3;
					temp=0;
				}
			}
			if(temp>3)
				pt+=temp-3;
			temp=0;
			for(l=0;l<=j-1;l++)
			{
				if(matrix[l+1][j-l]=='x')
					temp++;
				else
				{
					if(temp>3)
						pt+=temp-3;
					temp=0;
				}
			}
			if(temp>3)
				pt+=temp-3;
			temp=0;
			for(l=0;l<=n-j;l++)
			{
				if(matrix[l+1][j+l]=='x')
					temp++;
				else
				{
					if(temp>3)
						pt+=temp-3;
					temp=0;
				}
			}
			if(temp>3)
				pt+=temp-3;
			temp=0;
		}
		for(i=1;i<=n;i++)
		{
			for(l=1;l<=n;l++)
			{
				if(matrix[i][l]=='x')
					temp++;
				else
				{
					if(temp>3)
						pt+=temp-3;
					temp=0;
				}
			}
			if(temp>3)
				pt+=temp-3;
			temp=0;
			if(i>1)
			{
				for(l=0;l<=n-i;l++)
				{
					if(matrix[i+l][l+1]=='x')
						temp++;
					else
					{
						if(temp>3)
							pt+=temp-3;
						temp=0;
					}
				}
				if(temp>3)
					pt+=temp-3;
				temp=0;
				for(l=0;l<=n-i;l++)
				{
					if(matrix[i+l][n-l]=='x')
						temp++;
					else
					{
						if(temp>3)
							pt+=temp-3;
						temp=0;
					}
				}
				if(temp>3)
					pt+=temp-3;
				temp=0;
			}
		}
		cout<<pt<<endl;
	}
	return 0;
}